version: '3.0'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: chatroom
      MYSQL_ROOT_PASSWORD: 123456
    # volumes:
    #   - ./test/tmp_databases/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p123456" ]
      interval: 5s
      retries: 10
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8080:8080